### PR TITLE
added my json file

### PR DESCRIPTION
**Pull request by Aryan-beast**

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@Aryan-beast You need to paste the screenshot here in github into the PR description, not add it as a file. Just remove the screenshot file and paste it as comment here, I'll accept this PR then.

**Comment by Aryan-beast** [comment]
screenshot

**Comment by Aryan-beast** [comment]
maam done

**Comment by N-Shar-ma** [comment]
Can you add a screenshot of the endpoint with your roll number? This screenshot is what was required in the issue #1. This is the last step :)

**Comment by Aryan-beast** [comment]
screenshot-1

**Comment by Aryan-beast** [comment]
maam done

**Pull request closed without merging**
