### PR TITLE
Profile updated

### PR DESCRIPTION
**Pull request by laveshverma007**
Screenshot (346)

solves https://github.com/N-Shar-ma/FOSS-Weekend-Participants-API/issues/1

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@laveshverma007 The json and screenshot look good, however you were not asked to make any changes in the index.html file so please remove those. Also, mention the issue being solved in the PR description by simply editing it to add in a line like "solves #1"

Do these couple of things, and I'll accept this PR!

**Comment by laveshverma007** [comment]
> @laveshverma007 The json and screenshot look good, however you were not asked to make any changes in the index.html file so please remove those. Also, mention the issue being solved in the PR description by simply editing it to add in a line like "solves #1"
> 
> Do these couple of things, and I'll accept this PR!

sorry ma'am for the inconvenience, solved the issues.

**Comment by N-Shar-ma** [comment]
@laveshverma007 No need to apologise, nice work implementing the feedback :)

**Comment by laveshverma007** [comment]
> @laveshverma007 No need to apologise, nice work implementing the feedback :)

Thank you ma'am

**Pull request closed without merging**
