### PR TITLE
#1 issue. added profile.json

### PR DESCRIPTION
**Pull request by codermeet2003**
image

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@codermeet2003 This looks fine, just add the required screenshot as instructed in the issue

**Comment by codermeet2003** [comment]
maam I have added the screenshot in comment. its probably looking like a text because of dark mode

**Comment by codermeet2003** [comment]
also maam can you explain how to view the profile on browser using that local host number

**Comment by N-Shar-ma** [comment]
> maam I have added the screenshot in comment. its probably looking like a text because of dark mode

I mean the screenshot of your browser window.


> also maam can you explain how to view the profile on browser using that local host number

Did you try following the 3rd point in the local setup instructions in the readme?

**Comment by codermeet2003** [comment]
maam can you please check the screenshot now?

**Comment by codermeet2003** [comment]
maam can you please check the screenshot now

**Comment by N-Shar-ma** [comment]
@codermeet2003 The json looks fine now, however there is no screenshot of the browser window in this PR. Please add it as a comment here, or edit your PR message and paste it there

**Comment by codermeet2003** [comment]
image

**Comment by codermeet2003** [comment]
can you see the screenshot now ma'am?

**Comment by N-Shar-ma** [comment]
> can you see the screenshot now ma'am?

Yes, but could your screenshot show the url in the browser as well? Look at the example screenshot in the issue for reference

**Comment by codermeet2003** [comment]
image_2022-03-11_124211

**Comment by N-Shar-ma** [comment]
@codermeet2003 Accepted! Next time onwards please read the issue carefully to understand what exactly you need to do, so that the process is faster and easier for everyone involved

**Comment by codermeet2003** [comment]
yes ma'am. really sorry for the inconvenience. I couldn't follow the steps properly because its my 1st time using GitHub. Will work efficiently next time onwards.

**Pull request closed without merging**
