### PR TITLE
ADDING THE DETAILS 

### PR DESCRIPTION
**Pull request by palashb01**
palash_ss

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@palashb01 Please read the issue carefully again. The screenshot is correct but needs to be pasted into the PR description, not added as a file. Also I cannot see any code change? Refer to other accepted PRs for this issue, to get a better idea

**Comment by palashb01** [comment]
@N-Shar-ma Ma'am kindly recheck the screenshot and the codes that have been changed.

**Comment by N-Shar-ma** [comment]
@palashb01 That's better than before! But only make the changes asked for: remove all changes to index.html as that was not asked for. Also you have to add your profile, not replace the dummy one.

**Comment by palashb01** [comment]
@N-Shar-ma  ma'am kindly recheck it and let me know the required changes

**Pull request closed without merging**
