### PR TITLE
Added profile

### PR DESCRIPTION
**Pull request by VidishaAG**
Screenshot (192)

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@VidishaAG The screenshot looks fine! However, please read the issue carefully and make the necessary changes (hint: you have to add, not replace a profile), to have this PR accepted. Also mention the issue being fixed in the PR description like "solves #1"

**Comment by VidishaAG** [comment]
Screenshot (192)
Thank you for pointing out the issue ma'am! I updated the profiles.json to add another profile rather than replacing it.

**Comment by N-Shar-ma** [comment]
@Vidisha9 Nice! Just edit the PR description (that is the area where your screenshot is) to mention the issue, and I'll accept this

**Comment by N-Shar-ma** [comment]
Also try to just use one GitHub profile, otherwise it overcomplicates things for everyone

**Comment by VidishaAG** [comment]
> Also try to just use one GitHub profile, otherwise it overcomplicates things for everyone

Sorry ma'am , I did not realize I was making changes from the other profile. I will be mindful of it.
Also, I have edited the post to mention the issue.

**Pull request closed without merging**
