### PR TITLE
Added Profile

### PR DESCRIPTION
**Pull request by AlphaGaurav7**
#1 
JSON file after updation, locally hosted by npm:
image

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 You're missing a screenshot in the PR description, read the issue carefully!

Also could you explain what caused the change in the package-lock.json? This won't affect your score, just curious since another PR had the same issue

**Comment by AlphaGaurav7** [comment]
Sorry sorry, I'll do that. I'm not sure why but ~1800 lines of code were deleted from that file. All I had done was install npm and run, no idea why it affected the packages-locked file

**Comment by AlphaGaurav7** [comment]
There, updated. I had to copy the og code from your repo and refresh the file on my end, worked fine after that.

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 No problem regarding the package-lock. That weird issue does pop up sometimes for me too, probably due to difference in npm / package versions. Just wanted to verify what's up.

The screenshot still isn't quite right though! Observe the example screenshot more closely.

**Comment by AlphaGaurav7** [comment]
Updated it again, please tell me it's accepted this time ;-;

**Pull request closed without merging**
