### PR TITLE
Fixed issue #9: Create new endpoint for getting roll numbers of all participants

### PR DESCRIPTION
**Pull request by Ilikepizza2**
Fixed issue #9   by making changes to index.html and profiles.js
Screenshots are attached below:
1.  Home Page
157905061-3e7d6165-3c1b-44d6-a3d0-5fed9b9a5cf5
2. All roll numbers displayed on clicking the third link on home page
157905067-aa339fce-14af-45b7-8871-ab30d9956fe8

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Please remove the changes you had made for issue #1. Also you shouldn't have local host in the url as this won't work if this API is hosted somewhere. Always keep in mind that localhost only works for development purposes. Use a relative link instead (observe the other links in index.html for reference) that always works, whether in development or production

**Comment by Ilikepizza2** [comment]
Yes I did all the things mentioned in the comment. I'm sorry for the slightly late response.

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Accepted! But do see PR #56 as the code in `routes/profile.js` is slightly cleaner, so you can learn more from it for next time :)

**Comment by Ilikepizza2** [comment]
Yeah sure thank you ma'am :D

**Pull request closed without merging**
